create database if not exists customer_behavior_analysis;
use customer_behavior_analysis;

select * from customer_behavior;

-- 1.Which category generates highest revenue

select category ,round(sum(purchase_amount),2) as highest_revenue
from customer_behavior
group by category
order by highest_revenue desc;

-- bussiness problem : company does not know which category contibutes most revenue
-- Impact : 
			-- Helps prioritize high-performing categories
            -- Optimizes inventory planning
            -- Improves marketing ROI

-- 2. Are discount actually increasing purchase value?

select discount_applied ,
round(sum(purchase_amount),2) as Total_revenue,
round(avg(purchase_amount),2) as  avg_purchase
from customer_behavior
group by discount_applied ;

-- Business Problem : Discount may reduce profit without increasing sales

-- Impact : 
		   -- Identify effectivness of discounts
           -- Reducr unnecessary discount costs 
           -- Improve profit margins

-- 3. What is the total revenue generated by male and female customer?

select gender , round(sum(purchase_amount),2) as highest_revenue
from customer_behavior
group by gender
order by highest_revenue desc;

Lack of understanding of revenue contribution by gender segments.

-- 4. Which customer used a discount but still spent more then the average purchase amount?

select customer_id, purchase_amount, discount_applied
from customer_behavior
where discount_applied = 'yes' and purchase_amount > (select avg(purchase_amount) from customer_behavior)
limit 10;

--   Bussiness Problem : company cannot identify high-spending customers who are also discount users.

--   Impact : 
			 -- Identifies premium discount-sensitive customers
             -- Enables targeted discount campaigns
             -- Improves customer retention and revenue

-- 5. Which aree the top/bottom 5 products with the highest average review rating?
select * from customer_behavior;

select item_purchased , round(avg(review_rating),2) as avg_ratings
from customer_behavior
group by item_purchased
order by avg_ratings desc
limit 5;

select item_purchased , round(avg(review_rating),2) as avg_ratings
from customer_behavior
group by item_purchased
order by avg_ratings 
limit 5;

--    Business Problem: No visibility into product performance based on customer satisfaction.

--    Impact:
			 -- Promotes high-performing products 
             -- Improves low-rated products
             -- Enhance customer experience

-- 6. Average Purchase: Standard vs Express shipping
select * from customer_behavior;

select shipping_type , count(distinct customer_id) as order_placed , round(avg(purchase_amount),2) as avg_purchase , round(sum(purchase_amount) ,2)as revenue
from customer_behavior
where shipping_type = 'Express' or shipping_type = 'Standard'
group by shipping_type
order by revenue desc;

--    Business Problem : Unclear if faster shipping leads to higher spending

--    Impact:
			 -- Helps optimize shipping pricing strategy
             -- Encourages premium shipping adoption
             -- Increases average order value
             
--  7. Do subscribe customers spend more? compare average speed and total revenue between subscribers and non-subscribers.
select * from customer_behavior;

select 
subscription_status ,
count(distinct customer_id) as total_users,
round(sum(purchase_amount),2) as total_revenue,
round(avg(purchase_amount),2) as avg_revenue
from customer_behavior
group by subscription_status;

--    Business Problem: The effectivness of subscription programs is unknown

--    Impact: 
			-- Validates subscription model performance
            -- Improves customers loyalty programs
            -- Increases customer lifitime value (CLV)

-- 8. Top 5 products with highest discount usage %
select * from customer_behavior;

select item_purchased ,
count(item_purchased) as total_no_of_times_sold,
count(case when discount_applied = 'Yes' then 1 end) as total_no_of_times_discount_applied,
count(case when discount_applied = 'Yes' then 1 end)*100.0/count(*) as discount_percent
from customer_behavior
group by item_purchased 
order by discount_percent desc  
limit 5;

-- Business Problem: Some products may be overly dependent on discounts.

-- Impact:
		  -- Identifies discount-driven products
          -- Helps optimize pricing strategy
          -- Reduces profit margin loss

-- 9. segment customer into new, returning and loyal based on their tltal number of previous purchase,
	-- and show the count of each segment
    
select * from customer_behavior;

select 
	case 
		when previous_purchases = '0' then 'New Customer'
		when previous_purchases between 1 and 15 then 'Returning Customer'
	else 'Loyal Customers'
end as customer_segment,
count(*) as customer_count
from customer_behavior
group by customer_segment
order by customer_count desc;

--   Business Problem: Lack of customer segmentation leads to generic strategies

--   Impact: 
			-- Enables personalized marketing
            -- Improves retention strategies
            -- Increase conversion rates

-- 10. What are the top 3 most purchased products within each category?

select * from customer_behavior;

with CTE as(
select  category , item_purchased ,count(item_purchased) as most_purchased,
rank() over(partition by category order by count(item_purchased) desc) as ranks
from customer_behavior
group by category,item_purchased
) 
select * from CTE 
where ranks <= 3;

--   Business Problem: The company doesn't know top-performing products within categories.

--   Impact: 
			-- Improves product placement & recommendations
            -- Helps inventory optimization
            -- Increase sales through best-sellers
            
-- 11. Are customers who are repeat buyers (more than 5 previous purchase) also likely to subscribe?

select * from customer_behavior;

select 
	case
		when previous_purchases > 5 then 'Repeat Buyers'
        Else 'Normal Buyers'
	end as customer_type,
    subscription_status,
    count(*) as customer_count,
    count(*) * 100/sum(count(*)) over (partition by case 
										when previous_purchases > 5 then 'Repeat Buyers'
                                        else 'Normal Buyers'
                                        end
                                        ) as percents
from customer_behavior
group by customer_type ,subscription_status;

--    Business Problem: Unclear relationship between loyalty and subscription

--    Impact:
			-- Improves subscription targeting
            -- Increases conversion to paid programs
            -- Increase customer retention strategy

-- 12. What is the revenue contribution of each age group?

select * from customer_behavior;

select 
	case
		when age between 18 and 25 then '18-25'
		when age between 26 and 35 then '26-35'
		when age between 36 and 50 then '36-50'
        else '51+'
	end as age_group,
    round(sum(purchase_amount),2)as total_revenue
    from customer_behavior
    group by age_group
    order by total_revenue desc;